name: rayssa_delivery
repository: https://github.com/rayssa-delivery/rayssa-delivery

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    run: melos exec -- dart analyze
    description: Run analyzer in all packages
  test:
    run: melos exec -- dart test
    description: Run tests in all packages
